### ISSUE TITLE
No results after 01 June 2021

### ISSUE THREAD

**Issue by chrismelis** [WeNeedThePoh/euromillions-api#1]
Hi,
Thanks for this great API.
I am not sure if this is an issue or is something else.
The API can fetch the results up to 1st of June 2021.

**Comment by WeNeedThePoh** [comment]
Hi there!
Thanks for reporting.

Seems like an issue parsing the new results, I will take a look and fix it.

**Comment by WeNeedThePoh** [comment]
I just pushed a fix for the issue. All the draws from 2021-06-01 onwards are now available!
Also, all future draws will be stored correctly too.

Thanks!

**Comment by chrismelis** [comment]
Many thanks
